# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build-mac:
    macos:
        xcode: 12.5.0
    steps:
      - checkout
      - run:
          name: Setup submodules
          command: |
            cd submodules
            git submodule update --init --recursive
      - run:
          name: Setup cmake and build
          command: |
            mkdir build
            cd build
            cmake ..
            cmake --build
  build-win:
    executor: win/default # executor type
    environment:
      - CMAKE_DIR: 'C:\Program Files\CMake\bin'
    steps:
      - checkout

      - run:
          name: Setup submodules
          command: |
            cd submodules
            git submodule update --init --recursive

      - run:
          name: install cmake
          command: |
            choco install cmake
            $Env:PATH += ";$Env:CMAKE_DIR"

      - run:
          name: Setup cmake and build
          command: |
            mkdir build
            cd build
            cmake ..
            cmake --build


workflows:
  build:
    jobs:
      - build-win
      - build-mac

