"/smoveto { transform round exch round exch itransform moveto } def\n"
"/slineto { transform round exch round exch itransform lineto } def\n"
"/dotplain {\n"
"   /y exch def\n"
"   /x exch def\n"
"   newpath\n"
"   x y w 0 360 arc\n"
"   closepath\n"
"   stroke\n"
"} bind def\n"
"/dotsolid {\n"
"   /y exch def\n"
"   /x exch def\n"
"   newpath\n"
"   x y w 0 360 arc\n"
"   closepath\n"
"   fill\n"
"} bind def\n"
"/dotbs {\n"
"   /y exch def\n"
"   /x exch def\n"
"   newpath\n"
"   x y w 0 360 arc\n"
"   closepath\n"
"   stroke\n"
"   x plinew sub y plinew add smoveto\n"
"   x plinew add y plinew sub slineto\n"
"   stroke\n"
"} bind def\n"
"/dotsl {\n"
"   /y exch def\n"
"   /x exch def\n"
"   newpath\n"
"   x y w 0 360 arc\n"
"   closepath\n"
"   stroke\n"
"   x plinew add y plinew add smoveto\n"
"   x plinew sub y plinew sub slineto\n"
"   stroke\n"
"} bind def\n"
"/dotx {\n"
"   /y exch def\n"
"   /x exch def\n"
"   newpath\n"
"   x y w 0 360 arc\n"
"   closepath\n"
"   stroke\n"
"   x plinew sub y plinew add smoveto\n"
"   x plinew add y plinew sub slineto\n"
"   stroke\n"
"   x plinew add y plinew add smoveto\n"
"   x plinew sub y plinew sub slineto\n"
"   stroke\n"
"} bind def\n"
"/dotsolbs {\n"
"   /y exch def\n"
"   /x exch def\n"
"   newpath\n"
"   x y w 0 360 arc\n"
"   closepath\n"
"   fill\n"
"   x slinew sub y slinew add smoveto\n"
"   x slinew add y slinew sub slineto\n"
"   stroke\n"
"} bind def\n"
"/dotsolsl {\n"
"   /y exch def\n"
"   /x exch def\n"
"   newpath\n"
"   x y w 0 360 arc\n"
"   closepath\n"
"   fill\n"
"   x slinew add y slinew add smoveto\n"
"   x slinew sub y slinew sub slineto\n"
"   stroke\n"
"} bind def\n"
"/dotsolx {\n"
"   /y exch def\n"
"   /x exch def\n"
"   newpath\n"
"   x y w 0 360 arc\n"
"   closepath\n"
"   fill\n"
"   x slinew sub y slinew add smoveto\n"
"   x slinew add y slinew sub slineto\n"
"   stroke\n"
"   x slinew add y slinew add smoveto\n"
"   x slinew sub y slinew sub slineto\n"
"   stroke\n"
"} bind def\n"
"/leftText {\n"
"   x y moveto dup stringwidth pop x add /x exch def show\n"
"} bind def\n"
"/rightText {\n"
"   dup stringwidth pop\n"
"   rmargin exch sub\n"
"   y smoveto show\n"
"} bind def\n"
"/centerText {\n"
"   dup stringwidth pop 2 div\n"
"   rmargin lmargin sub 2 div\n"
"   exch sub\n"
"   lmargin add\n"
"   y smoveto show\n"
"} bind def\n"
"/drawTextfield {\n"
"   lmargin y smoveto rmargin y slineto stroke\n"
"   /y y h 1.1 mul sub def centerText\n"
"} bind def\n"
"/space_over {\n"
"   /x x ( ) stringwidth pop add def\n"
"} bind def\n"
"/do_tab {\n"
"   /tabnum exch def\n"
"   x tabnum lt {/x tabnum def} {space_over} ifelse\n"
"} bind def\n"
"/donumber {\n"
"   w 1.25 mul add /y exch def /rmargin exch def rightText\n"
"} bind def\n"
"/donumber2 {\n"
"   w 1.25 mul add /y exch def /x exch def leftText\n"
"} bind def\n"
"/drawwhash {\n"
"   x y smoveto x w 10 div add y slineto stroke\n"
"   x w .9 mul add y smoveto x w add y slineto stroke\n"
"   x w .2 mul add dup y smoveto y w .2 mul sub slineto stroke\n"
"   x w .4 mul add dup y smoveto y w .2 mul sub slineto stroke\n"
"   x w .6 mul add dup y smoveto y w .2 mul sub slineto stroke\n"
"   x w .8 mul add dup y smoveto y w .2 mul sub slineto stroke\n"
"} bind def\n"
"/drawehash {\n"
"   x y smoveto x w 10 div add y slineto stroke\n"
"   x w .9 mul add y smoveto x w add y slineto stroke\n"
"   x w .2 mul add dup y smoveto y w .2 mul add slineto stroke\n"
"   x w .4 mul add dup y smoveto y w .2 mul add slineto stroke\n"
"   x w .6 mul add dup y smoveto y w .2 mul add slineto stroke\n"
"   x w .8 mul add dup y smoveto y w .2 mul add slineto stroke\n"
"} bind def\n"
"/doarrows {\n"
"   /mainfont findfont fieldw stepw div 1.5 mul scalefont setfont\n"
"   /x fieldw stepw div def\n"
"   /lmargin 0 def /rmargin fieldw stepw div 8 mul def\n"
"   /y fieldw neg stepw div 4 mul def\n"
"   newpath rmargin y smoveto 0 y slineto stroke\n"
"   x y x sub smoveto 0 y slineto x y x add slineto stroke\n"
"   /y y x sub fieldw stepw div 1.5 mul sub def (south) centerText\n"
"   /y fieldw stepw div 4 mul fieldh add def\n"
"   newpath rmargin y smoveto 0 y slineto\n"
"   x y x sub smoveto 0 y slineto x y x add slineto stroke\n"
"   /y y x add def (south) centerText\n"
"   /lmargin fieldw dup stepw div 8 mul sub def /rmargin fieldw def\n"
"   /y fieldw neg stepw div 4 mul def\n"
"   newpath lmargin y smoveto rmargin y slineto\n"
"   rmargin x sub y x sub smoveto\n"
"   rmargin y slineto\n"
"   rmargin x sub y x add slineto stroke\n"
"   /y y x sub fieldw stepw div 1.5 mul sub def (north) centerText\n"
"   /y fieldw stepw div 4 mul fieldh add def\n"
"   newpath lmargin y smoveto rmargin y slineto\n"
"   rmargin x sub y x sub smoveto\n"
"   rmargin y slineto\n"
"   rmargin x sub y x add slineto stroke\n"
"   /y y x add def (north) centerText\n"
"   /lmargin fieldw .9 mul def /rmargin fieldw def\n"
"   newpath lmargin fieldy neg smoveto\n"
"   rmargin fieldy neg slineto\n"
"   rmargin fieldw stepw div 4 mul fieldy sub slineto\n"
"   lmargin fieldw stepw div 4 mul fieldy sub slineto closepath stroke\n"
"   /mainfont findfont fieldw stepw div 3 mul scalefont setfont\n"
"   /y fieldw stepw div 2 div fieldy sub def pagenumtext centerText\n"
"} bind def\n"
"/drawfield {\n"
"   newpath 0 0 smoveto\n"
"   0 fieldh slineto\n"
"   fieldw fieldh slineto\n"
"   fieldw 0 slineto\n"
"   closepath stroke\n"
"   /w fieldw stepw div 8 mul def\n"
"   /x w def stepw 8 idiv 1 sub {\n"
"      x 0 smoveto x fieldh slineto stroke /x x w add def\n"
"   } repeat\n"
"   [ fieldw stepw div ] 0 setdash\n"
"   /x w 2 div def stepw 8 idiv {\n"
"      x fieldh smoveto x 0 slineto stroke /x x w add def\n"
"   } repeat\n"
"   4 4 80 {\n"
"       dup dup 84 whash sub ne exch 84 ehash sub ne and {\n"
"          dup fieldh 84 div mul 0 exch smoveto\n"
"          fieldh 84 div mul fieldw exch slineto stroke\n"
"       } if\n"
"   } for\n"
"   [] 0 setdash\n"
"   /y fieldh 84 whash sub mul 84 div def\n"
"   /x 0 def stepw 8 idiv {drawwhash /x x w add def} repeat\n"
"   /y fieldh 84 ehash sub mul 84 div def\n"
"   /x 0 def stepw 8 idiv {drawehash /x x w add def} repeat\n"
"   doarrows\n"
"   /headfont findfont fieldw stepw div headsize mul scalefont setfont\n"
"   /lmargin 0 def /rmargin fieldw def\n"
"   /y fieldw stepw div 16 headsize sub mul fieldh add def\n"
"   (UNIVERSITY OF CALIFORNIA MARCHING BAND) centerText\n"
"   /h fieldw stepw div 1.5 mul def\n"
"   /mainfont findfont h scalefont setfont\n"
"   /lmargin fieldw 4 div def /rmargin fieldw .75 mul def\n"
"   /y fieldw stepw div 8 mul fieldh add def\n"
"   (Music) drawTextfield\n"
"   /y fieldw stepw div 4 mul fieldh add def\n"
"   (Formation) drawTextfield\n"
"   /lmargin 0 def /rmargin fieldw 8 div def\n"
"   /y fieldw stepw div 10 mul fieldh add def\n"
"   (game) drawTextfield\n"
"   /lmargin fieldw .875 mul def /rmargin fieldw def\n"
"   /y fieldw stepw div 10 mul fieldh add def\n"
"   (page) drawTextfield\n"
"   /mainfont findfont fieldw stepw div 3 mul scalefont setfont\n"
"   /y fieldw stepw div 10.5 mul fieldh add def pagenumtext centerText\n"
"   /mainfont findfont fieldw stepw div yardsize mul scalefont setfont\n"
"   /lmargin 0 def /rmargin fieldw def\n"
"   /y fieldw neg stepw div 8 mul def\n"
"   (CAL SIDE) centerText\n"
"} bind def\n"
"/ReencodeFont {\n"
"   findfont\n"
"   dup length 1 add dict begin\n"
"      {1 index /FID ne {def} {pop pop} ifelse} forall\n"
"      /Encoding exch def\n"
"      currentdict\n"
"   end\n"
"   definefont pop\n"
"} bind def\n"
