"/smoveto { transform round exch round exch itransform moveto } def\n"
"/slineto { transform round exch round exch itransform lineto } def\n"
"/dotbox {\n"
"   /y exch def\n"
"   /x exch def\n"
"   newpath\n"
"   x w sub y w sub smoveto\n"
"   x w add y w sub slineto\n"
"   x w add y w add slineto\n"
"   x w sub y w add slineto\n"
"   closepath\n"
"   fill\n"
"} bind def\n"
"/drawfield {\n"
"   newpath 0 0 smoveto\n"
"   0 fieldh slineto\n"
"   fieldw fieldh slineto\n"
"   fieldw 0 slineto\n"
"   closepath stroke\n"
"   0 84 ehash sub fieldh mul 84 div smoveto\n"
"   .2 fieldw mul 20 div 84 ehash sub fieldh mul 84 div slineto stroke\n"
"   19.8 fieldw mul 20 div 84 ehash sub fieldh mul 84 div smoveto\n"
"   fieldw 84 ehash sub fieldh mul 84 div slineto stroke\n"
"   0 84 whash sub fieldh mul 84 div smoveto\n"
"   .2 fieldw mul 20 div 84 whash sub fieldh mul 84 div slineto stroke\n"
"   19.8 fieldw mul 20 div 84 whash sub fieldh mul 84 div smoveto\n"
"   fieldw 84 whash sub fieldh mul 84 div slineto stroke\n"
"   1 1 19 {\n"
"      dup fieldw mul 20 div dup 0 smoveto fieldh slineto stroke\n"
"      dup .2 sub fieldw mul 20 div 84 ehash sub fieldh mul 84 div smoveto\n"
"      dup .2 add fieldw mul 20 div 84 ehash sub fieldh mul 84 div slineto stroke\n"
"      dup .2 sub fieldw mul 20 div 84 whash sub fieldh mul 84 div smoveto\n"
"      .2 add fieldw mul 20 div 84 whash sub fieldh mul 84 div slineto stroke\n"
"   } for\n"
"} bind def\n"
